### ISSUE TITLE
Title (English): Error enabling and disabling AxMinions v1.0.11 on Minecraft 1.21.1 Title (Spanish): Error al habilitar y deshabilitar AxMinions v1.0.11 en Minecraft 1.21.1

### ISSUE THREAD

**Issue by servicomcr** [Artillex-Studios/AxMinions#33]
Report (English):
An error occurred while enabling and disabling the AxMinions plugin version 1.0.11 on a Minecraft 1.21.1 server. The error stems from uninitialized lateinit properties (INSTANCE and dataHandler) in Kotlin, causing UninitializedPropertyAccessException during plugin start and shutdown. This makes the plugin non-functional. Here is part of the error log:

python
Copiar código
kotlin.UninitializedPropertyAccessException: lateinit property INSTANCE has not been initialized
at AxMinions-1.0.11-all.jar/com.artillexstudios.axminions.api.AxMinionsAPI$Companion.getINSTANCE(AxMinionsAPI.kt:34) ~[AxMinions-1.0.11-all.jar:?]
...
kotlin.UninitializedPropertyAccessException: lateinit property dataHandler has not been initialized
at AxMinions-1.0.11-all.jar/com.artillexstudios.axminions.AxMinionsPlugin$Companion.getDataHandler(AxMinionsPlugin.kt:49) ~[AxMinions-1.0.11-all.jar:?]
Report (Spanish):
Ocurrió un error al habilitar y deshabilitar el plugin AxMinions versión 1.0.11 en un servidor Minecraft 1.21.1. El error proviene de propiedades lateinit no inicializadas (INSTANCE y dataHandler) en Kotlin, lo que causa UninitializedPropertyAccessException durante el inicio y apagado del plugin. Esto hace que el plugin no funcione. A continuación, se muestra parte del registro de errores:

python
Copiar código
kotlin.UninitializedPropertyAccessException: lateinit property INSTANCE has not been initialized
at AxMinions-1.0.11-all.jar/com.artillexstudios.axminions.api.AxMinionsAPI$Companion.getINSTANCE(AxMinionsAPI.kt:34) ~[AxMinions-1.0.11-all.jar:?]
...
kotlin.UninitializedPropertyAccessException: lateinit property dataHandler has not been initialized
at AxMinions-1.0.11-all.jar/com.artillexstudios.axminions.AxMinionsPlugin$Companion.getDataHandler(AxMinionsPlugin.kt:49) ~[AxMinions-1.0.11-all.jar:?]

**Comment by AverageGithub** [comment]
Update to 1.0.12
