### ISSUE TITLE
 Could not pass event BlockPlaceEvent to AxMinions

### ISSUE THREAD

**Issue by dugesti** [Artillex-Studios/AxMinions#39]
[15:57:15] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to AxMinions v1.0.11
com.artillexstudios.axminions.libs.h2.jdbc.JdbcSQLNonTransientConnectionException: (Message 90098 not found) [90098-220]
	at com.artillexstudios.axminions.libs.h2.message.DbException.getJdbcSQLException(DbException.java:690) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.libs.h2.message.DbException.getJdbcSQLException(DbException.java:489) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.libs.h2.message.DbException.get(DbException.java:212) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.libs.h2.engine.SessionLocal.getTransaction(SessionLocal.java:1606) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.libs.h2.engine.SessionLocal.startStatementWithinTransaction(SessionLocal.java:1627) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.libs.h2.command.Command.executeQuery(Command.java:185) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.libs.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:128) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.libs.hikaricp.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.libs.hikaricp.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.data.H2DataHandler.isMinion(H2DataHandler.kt:375) ~[AxMinions-1.0.12-all.jar:?]
	at com.artillexstudios.axminions.listeners.MinionPlaceListener.onBlockPlace(MinionPlaceListener.kt:211) ~[AxMinions-1.0.12-all.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor831.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:383) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:625) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1852) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by dugesti** [comment]
❤️
