### ISSUE TITLE
AxMinions Whenever I remove the minion with a charge and a level, this message appears on the console.

### ISSUE THREAD

**Issue by ThePancakeFlipper** [Artillex-Studios/AxMinions#40]
Whenever I remove the minion with a charge and a level, this message appears on the console. And I can't put any other minions back.

versions in which this happens:

paper Version: 1.21.1-132

Current log
Purpur Version: 1.21.1-2329-803bf62

[02:23:03 WARN]: Exception in thread "AxMinions-Database-Queue" java.lang.NoSuchFieldError: Class org.bukkit.craftbukkit.util.CraftMagicNumbers does not have member field 'org.bukkit.UnsafeValues INSTANCE'
[02:23:03 WARN]:        at AxMinions-1.0.12-all.jar//com.artillexstudios.axminions.libs.axapi.nms.v1_21_R1.ItemStackSerializer.serializeAsBytes(ItemStackSerializer.java:27)
[02:23:03 WARN]:        at AxMinions-1.0.12-all.jar//com.artillexstudios.axminions.libs.axapi.nms.v1_21_R1.items.WrappedItemStack.serialize(WrappedItemStack.java:62)
[02:23:03 WARN]:        at AxMinions-1.0.12-all.jar//com.artillexstudios.axminions.libs.axapi.serializers.impl.ItemStackSerializer.serialize(ItemStackSerializer.java:12)
[02:23:03 WARN]:        at AxMinions-1.0.12-all.jar//com.artillexstudios.axminions.libs.axapi.serializers.impl.ItemStackSerializer.serialize(ItemStackSerializer.java:8)
[02:23:03 WARN]:        at AxMinions-1.0.12-all.jar//com.artillexstudios.axminions.data.H2DataHandler.saveMinion(H2DataHandler.kt:302)
[02:23:03 WARN]:        at AxMinions-1.0.12-all.jar//com.artillexstudios.axminions.minions.Minion.setTool$lambda$11(Minion.kt:456)
[02:23:03 WARN]:        at AxMinions-1.0.12-all.jar//com.artillexstudios.axminions.libs.axapi.data.ThreadedQueue.run(ThreadedQueue.java:56)
[02:23:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by notfifteen** [comment]
same issue
